### PR TITLE
Repo to maintain subgraphs

### PR DESCRIPTION
**Pull request by Chaitanya2801**
### This PR includes following changes:
- A eeadme.md file was created in which title description and a table is created.
- Following subgraphs added:
    1. Aztec
    2. Celo attestation subgraph
    3. Celo token analytics
    4. Moola V2
    5. Moonbeam XCM
    6. Optics V2
    7. Paraswap
    8. Polygon Bridge
    9. Polygon Root Chain Manager
- Changes made to the aztec subgraph
    1. Entity attribute `blocktimestamp` renamed to `timestamp` in various subgraphs.
    2. Removed `RoleAdminChanged` from list of entities.

### CODE REVIEW

**Comment by abhayait** [comment]
subgraphs/Aztec/dapplooker/asset-subgraph/abis/RP_.json
Path should be subgraphs/aztec-network/abis/abi.json

Remove dapplooker/asset-subgraph from folder path. cc @realchoubey 
Similar structure for other subgraphs. This subgraph belongs to https://aztec.network/ Dapp

**Comment by abhayait** [comment]
subgraphs/Polygon-Bridge/dapplooker/pan-swap/abis/ERC20_.json => subgraphs/polygon-bridge/abis/ERC20.json

Remove dapplooker/pan-swap from path

**Comment by abhayait** [comment]
subgraphs/Polygon-Root-Chain-Manager/dapplooker/nft1/abis/RCM_.json => subgraphs/polygon-root-chain-manager/abis/RCM.json

Remove dapplooker/nft1 from path

**Comment by abhayait** [comment]
- Why other subgraphs are added as submodules?
- Don't commit node_modules

**Review by realchoubey — APPROVED** [review]

**Pull request merged**
